In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [9]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [26]:
voc_size=500

In [27]:
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[7, 347, 98, 83], [7, 347, 98, 499], [7, 425, 98, 276], [81, 40, 479, 263, 354], [81, 40, 479, 263, 446], [18, 7, 344, 98, 96], [51, 480, 292, 263]]


In [28]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [29]:
import numpy as np

In [30]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0   7 347  98  83]
 [  0   0   0   0   7 347  98 499]
 [  0   0   0   0   7 425  98 276]
 [  0   0   0  81  40 479 263 354]
 [  0   0   0  81  40 479 263 446]
 [  0   0   0  18   7 344  98  96]
 [  0   0   0   0  51 480 292 263]]


In [31]:
dim=10

In [32]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [34]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [35]:
embedded_docs[0]

array([  0,   0,   0,   0,   7, 347,  98,  83], dtype=int32)

In [36]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 113ms/step


array([[-0.03911148, -0.00122551, -0.04500958,  0.01643233,  0.02496053,
        -0.02070828,  0.01161424, -0.03829966, -0.03123219,  0.02763719],
       [-0.03911148, -0.00122551, -0.04500958,  0.01643233,  0.02496053,
        -0.02070828,  0.01161424, -0.03829966, -0.03123219,  0.02763719],
       [-0.03911148, -0.00122551, -0.04500958,  0.01643233,  0.02496053,
        -0.02070828,  0.01161424, -0.03829966, -0.03123219,  0.02763719],
       [-0.03911148, -0.00122551, -0.04500958,  0.01643233,  0.02496053,
        -0.02070828,  0.01161424, -0.03829966, -0.03123219,  0.02763719],
       [-0.03490331,  0.0319752 , -0.03841381,  0.02937684, -0.04478065,
        -0.03902419,  0.03348992, -0.00758822,  0.00587194, -0.04233864],
       [ 0.02852817,  0.04068387,  0.01310698, -0.01892045,  0.04053639,
         0.03525161,  0.01961699,  0.03232015, -0.03677924,  0.01110888],
       [ 0.00898656, -0.01559452,  0.04119713, -0.00081954, -0.01821595,
         0.0437947 , -0.01249756, -0.04447321

In [ ]:
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]